spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.application.name=chat-service
server.port=8091

# RabbitMQ Retry Config
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3

