# ==============================================================================
# ENTORNO DE PRODUCCIÓN (PROD) - bff-service
# ==============================================================================

# Microsoft Entra ID (Azure AD Production Tenant)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
bff.azure.api-audience=api://${AZURE_API_CLIENT_ID}

# URLs de Microservicios Backend (Red interna Docker / AWS Service Connect)
services.usuario-url=${USUARIO_SERVICE_URL:http://usuario:8081}
services.pedidos-url=${PEDIDOS_SERVICE_URL:http://pedidos:8082}
services.carrito-url=${CARRITO_SERVICE_URL:http://carrito:8083}
services.analitica-url=${ANALITICA_SERVICE_URL:http://analitica:8084}
services.productos-url=${PRODUCTOS_SERVICE_URL:http://productos:8085}
services.notificacion-url=${NOTIFICACION_SERVICE_URL:http://notificacion:8086}

# CORS
bff.frontend-origin=${FRONTEND_ORIGIN}

# Clave Interna de Comunicación entre Microservicios
bff.internal-key=${BFF_INTERNAL_KEY}
