# Perfil por defecto: dev (se puede sobrescribir con SPRING_PROFILES_ACTIVE=prod)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.application.name=bff-service
server.port=8090

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging Base
logging.level.cl.duoc.pedidos360.bff=INFO
logging.level.org.springframework.security=WARN
logging.level.org.springframework.web.reactive.function.client=WARN
