# ==============================================================================
# ENTORNO DE DESARROLLO (DEV) - bff-service
# ==============================================================================

# Microsoft Entra ID (Azure AD Local / Dev Tenant)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID:a50f6528-499a-4d94-bcad-ed9b200f7c7b}/v2.0
bff.azure.api-audience=api://${AZURE_API_CLIENT_ID:5febc8e2-ee14-4452-8914-7d237eb5a6f5}

# URLs de Microservicios Backend (Localhost)
services.usuario-url=${USUARIO_SERVICE_URL:http://localhost:8081}
services.pedidos-url=${PEDIDOS_SERVICE_URL:http://localhost:8082}
services.carrito-url=${CARRITO_SERVICE_URL:http://localhost:8083}
services.analitica-url=${ANALITICA_SERVICE_URL:http://localhost:8084}
services.productos-url=${PRODUCTOS_SERVICE_URL:http://localhost:8085}
services.notificacion-url=${NOTIFICACION_SERVICE_URL:http://localhost:8086}

# CORS
bff.frontend-origin=${FRONTEND_ORIGIN:http://localhost:4200}

# Clave Interna de Comunicación entre Microservicios
bff.internal-key=${BFF_INTERNAL_KEY:pedidos360-internal-secret-key-local-2026}
